<?php

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_form_field']['up_paypalEmail']			= array('PayPal E-Mail-Adresse für eingehende Zahlungen','Bitte geben Sie die PayPal E-Mail-Adresse ein, zu der Bezahlungen geleitet werden.');
$GLOBALS['TL_LANG']['tl_form_field']['up_paypalUrlParams']		= array('Url Parameter für PayPal Weiterleitung','Definieren Sie zusätzliche GET Parameter für die PayPal Url. Mehrere Parameter können mit einem & (kaufmannisch UND) übergeben werden. InsertTags sind erlaubt. Beispiel: <span style="font-style:italic">item_name=Mein+Artikel&amount=1.00</span>');
$GLOBALS['TL_LANG']['tl_form_field']['up_paypalDebug']			= array('Testsystem verwenden','Wählen Sie hier, wenn sie das PayPal Testsystem nutzen wollen.');
$GLOBALS['TL_LANG']['tl_form_field']['up_paypalJumpToComplete']	= array('Weiterleitungsseite nach Bezahlung','Wählen Sie die Seite, auf die der Benutzer nach der Bezahlung weitergeleitet werden soll.');